services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgis/postgis:${POSTGRES_VERSION:-17}-3.5-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hospes}
      POSTGRES_USER: ${POSTGRES_USER:-hospes}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hospes}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-hospes}", "-U", "${POSTGRES_USER:-hospes}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 60s
###< doctrine/doctrine-bundle ###

  php:
    build:
      context: .
      target: prod
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-hospes}:${POSTGRES_PASSWORD:-hospes}@database:5432/${POSTGRES_DB:-hospes}?serverVersion=${POSTGRES_VERSION:-17}&charset=utf8"
      APP_SECRET: "${APP_SECRET}"
    volumes:
      - jwt-keys:/app/config/jwt

  caddy:
    image: caddy:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/app/public:ro
    depends_on:
      - php

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      #SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000 http://localhost:8000
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  jwt-keys:
  redis_data:

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
