services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-17}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-hospes}
      POSTGRES_USER: ${POSTGRES_USER:-hospes}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hospes}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-hospes}", "-U", "${POSTGRES_USER:-hospes}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 60s
###< doctrine/doctrine-bundle ###

  php:
    build:
      context: .
      target: prod
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-hospes}:${POSTGRES_PASSWORD:-hospes}@database:5432/${POSTGRES_DB:-hospes}?serverVersion=${POSTGRES_VERSION:-17}&charset=utf8"
      APP_SECRET: "${APP_SECRET}"
    volumes:
      - jwt-keys:/app/config/jwt

  caddy:
    image: caddy:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/app/public:ro
    depends_on:
      - php

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  jwt-keys:
