<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260412201202 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE host_legal_identifier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, value VARCHAR(100) NOT NULL, country VARCHAR(2) NOT NULL, is_verified BOOLEAN NOT NULL, verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, host_profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_469CEF07646948B1 ON host_legal_identifier (host_profile_id)');
        $this->addSql('CREATE TABLE host_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, business_name VARCHAR(200) NOT NULL, legal_form VARCHAR(50) DEFAULT NULL, country VARCHAR(2) NOT NULL, vat_number VARCHAR(20) DEFAULT NULL, billing_address VARCHAR(255) NOT NULL, billing_city VARCHAR(100) NOT NULL, billing_postal_code VARCHAR(10) NOT NULL, billing_country VARCHAR(2) NOT NULL, timezone VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B6AB863EA76ED395 ON host_profile (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(20) DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reset_token VARCHAR(100) DEFAULT NULL, reset_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE host_legal_identifier ADD CONSTRAINT FK_469CEF07646948B1 FOREIGN KEY (host_profile_id) REFERENCES host_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE host_profile ADD CONSTRAINT FK_B6AB863EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE host_legal_identifier DROP CONSTRAINT FK_469CEF07646948B1');
        $this->addSql('ALTER TABLE host_profile DROP CONSTRAINT FK_B6AB863EA76ED395');
        $this->addSql('DROP TABLE host_legal_identifier');
        $this->addSql('DROP TABLE host_profile');
        $this->addSql('DROP TABLE "user"');
    }
}
