<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420110411 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE price_override (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, price INT NOT NULL, label VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lodging_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E0B53DF287335AF1 ON price_override (lodging_id)');
        $this->addSql('ALTER TABLE price_override ADD CONSTRAINT FK_E0B53DF287335AF1 FOREIGN KEY (lodging_id) REFERENCES lodging (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE price_override DROP CONSTRAINT FK_E0B53DF287335AF1');
        $this->addSql('DROP TABLE price_override');
    }
}
