<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420123136 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking_night (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, price INT NOT NULL, source VARCHAR(80) NOT NULL, booking_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_80A6F2223301C60 ON booking_night (booking_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_80A6F2223301C60AA9E377A ON booking_night (booking_id, date)');
        $this->addSql('ALTER TABLE booking_night ADD CONSTRAINT FK_80A6F2223301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE booking_night DROP CONSTRAINT FK_80A6F2223301C60');
        $this->addSql('DROP TABLE booking_night');
    }
}
