<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260416160739 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lodging (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, type VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, capacity INT NOT NULL, base_price_week INT NOT NULL, base_price_weekend INT NOT NULL, cleaning_fee INT DEFAULT NULL, tourist_tax_per_person INT DEFAULT NULL, deposit_amount INT DEFAULT NULL, cancellation_policy VARCHAR(255) NOT NULL, min_stay INT DEFAULT NULL, max_stay INT DEFAULT NULL, orphan_protection BOOLEAN DEFAULT false NOT NULL, checkin_time TIME(0) WITHOUT TIME ZONE NOT NULL, checkout_time TIME(0) WITHOUT TIME ZONE NOT NULL, address VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL, region VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(10) NOT NULL, country VARCHAR(2) NOT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, average_rating NUMERIC(3, 2) DEFAULT NULL, review_count INT DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, host_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D35182A1FB8D185 ON lodging (host_id)');
        $this->addSql('CREATE TABLE lodging_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url TEXT NOT NULL, alt_text VARCHAR(255) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lodging_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97BA929087335AF1 ON lodging_image (lodging_id)');
        $this->addSql('ALTER TABLE lodging ADD CONSTRAINT FK_8D35182A1FB8D185 FOREIGN KEY (host_id) REFERENCES host_profile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lodging_image ADD CONSTRAINT FK_97BA929087335AF1 FOREIGN KEY (lodging_id) REFERENCES lodging (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE host_profile DROP vat_number');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lodging DROP CONSTRAINT FK_8D35182A1FB8D185');
        $this->addSql('ALTER TABLE lodging_image DROP CONSTRAINT FK_97BA929087335AF1');
        $this->addSql('DROP TABLE lodging');
        $this->addSql('DROP TABLE lodging_image');
        $this->addSql('ALTER TABLE host_profile ADD vat_number VARCHAR(20) DEFAULT NULL');
    }
}
