<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260420111609 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE season (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(80) NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, price_week INT NOT NULL, price_weekend INT NOT NULL, min_stay INT DEFAULT NULL, max_stay INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lodging_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F0E45BA987335AF1 ON season (lodging_id)');
        $this->addSql('ALTER TABLE season ADD CONSTRAINT FK_F0E45BA987335AF1 FOREIGN KEY (lodging_id) REFERENCES lodging (id)');
        $this->addSql('ALTER TABLE price_override DROP CONSTRAINT fk_e0b53df287335af1');
        $this->addSql('DROP INDEX idx_e0b53df287335af1');
        $this->addSql('ALTER TABLE price_override ADD lodging VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE price_override DROP lodging_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE season DROP CONSTRAINT FK_F0E45BA987335AF1');
        $this->addSql('DROP TABLE season');
        $this->addSql('ALTER TABLE price_override ADD lodging_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE price_override DROP lodging');
        $this->addSql('ALTER TABLE price_override ADD CONSTRAINT fk_e0b53df287335af1 FOREIGN KEY (lodging_id) REFERENCES lodging (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_e0b53df287335af1 ON price_override (lodging_id)');
    }
}
